<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'EBT\\ExtensionBuilder\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Classes'),
    'Evoweb\\SfRegister\\' => array($typo3InstallDir . 'typo3conf/ext/sf_register/Classes'),
    'GeorgRinger\\News\\' => array($typo3InstallDir . 'typo3conf/ext/news/Classes'),
    'Mehrwert\\Phpmyadmin\\' => array($typo3InstallDir . 'typo3conf/ext/phpmyadmin/Classes'),
);
